apiVersion: v1
kind: Pod
metadata:
  name: client
spec:
  containers:
    - name: client
      image: cptscience/debugger:latest
      command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
