apiVersion: v1
kind: Namespace
metadata:
  name: contrail
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contrail-serviceaccount
  namespace: contrail
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contrail-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: contrail-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contrail-role
subjects:
- kind: ServiceAccount
  name: contrail-serviceaccount
  namespace: contrail
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contrail-k8s-deployer
  namespace: contrail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contrail-k8s-deployer
  template:
    metadata:
      labels:
        app: contrail-k8s-deployer
    spec:
      containers:
      - command:
        - sh
        - -c
        - /manager --metrics-addr 127.0.0.1:8081
        image: svl-artifactory.juniper.net/atom-docker/cn2/contrail-k8s-deployer:latest
        imagePullPolicy: Always
        name: contrail-k8s-deployer
      hostNetwork: true
      initContainers:
      - command:
        - sh
        - -c
        - kustomize build /crd | kubectl apply -f -
        image: svl-artifactory.juniper.net/atom-docker/cn2/contrail-k8s-crdloader:latest
        imagePullPolicy: Always
        name: contrail-k8s-crdloader
      nodeSelector:
        node-role.kubernetes.io/master: ""
      serviceAccountName: contrail-serviceaccount
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
---
apiVersion: batch/v1
kind: Job
metadata:
  name: apply-contrail
  namespace: contrail
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - command:
        - sh
        - -c
        - kubectl wait --for condition=established --timeout=60s   crd/apiservers.configplane.juniper.net
          && kubectl wait --for condition=established --timeout=60s crd/controllers.configplane.juniper.net
          && kubectl apply -k /manifests/kustomize/contrail/custom/latest
        image: svl-artifactory.juniper.net/atom-docker/cn2/contrail-k8s-applier:latest
        name: applier
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Never
      serviceAccountName: contrail-serviceaccount
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
