apiVersion: v1
kind: Pod
metadata:
  name: red-net-client
  namespace: multinet
  annotations:
    k8s.v1.cni.cncf.io/networks: red-vn
spec:
  containers:
    - name: red-net-client
      image: cptscience/debugger:latest
      command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
      securityContext:
        privileged: true
